import {z} from 'zod';
import {questions,validateAnswers,classify,countries} from '@/lib/assessment';
import {recommend,validateRevision} from '@/lib/engine';
import {config,db,now,uid,token,hash,fail,cookie,cookieHeader,query,first,event,limit,user,admin,owned,readAnswers,emailFrame,esc,sendMail,attachRecommendation,generate,reportMail} from '@/lib/server';
export const dynamic='force-dynamic';
function validated<T>(fn:()=>T):T{try{return fn();}catch(e:any){fail(e.message,400);}}
function json(data:any,status=200,cookies:string[]=[]){const h=new Headers({'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});cookies.forEach(c=>h.append('Set-Cookie',c));return new Response(JSON.stringify(data),{status,headers:h});}
async function handle(req:Request){try{const url=new URL(req.url),path=url.pathname.replace(/^\/api\//,'').split('/'),post=req.method==='POST';let b:any={};if(post){if(req.headers.get('origin')!==url.origin)fail('Request origin is not allowed.',403);if(!req.headers.get('content-type')?.includes('application/json'))fail('JSON required.',415);const text=await req.text();if(text.length>65000)fail('Request too large.',413);try{b=JSON.parse(text);}catch{fail('Invalid request.');}}
 const ip=req.headers.get('cf-connecting-ip')||'local';
 if(path[0]==='me'){const u=await user(req);return json({user:u?{name:u.name,email:u.email,country:u.country_name}:null,admin:!!await admin(req,false)});}
 if(path[0]==='visit'&&post){await limit('visit:'+await hash(ip),20);await event(null,'Site Visit').run();return json({ok:true});}
 if(path[0]==='logout'&&post){await db().prepare('DELETE FROM sessions WHERE token_hash=?').bind(await hash(cookie(req,'aic_session'))).run();return json({ok:true},200,[cookieHeader(req,'aic_session','',0)]);}
 if(path[0]==='assessments'&&post){await limit('start:'+await hash(ip),15,3600);const id=uid(),secret=token(),t=now();await db().batch([db().prepare('INSERT INTO assessments (id,owner_hash,status,created_at,updated_at) VALUES (?,?,?,?,?)').bind(id,await hash(secret),'Assessment Started',t,t),event(id,'Assessment Started')]);return json({id},201,[cookieHeader(req,'aic_draft',secret,86400)]);}
 if(path[0]==='assessment'){
 const id=path[1];const a=await owned(req,id);if(!post){const answers=await readAnswers(id);return json({assessment:a,answers});}
 if(a.user_id)fail('Verified assessments cannot be changed. Start a new assessment.',409);
 if(path[2]==='complete'){const answers=validated(()=>validateAnswers(b.answers));await db().batch([...Object.entries(answers).map(([q,v])=>db().prepare('INSERT INTO assessment_answers (id,assessment_id,question,answer) VALUES (?,?,?,?) ON CONFLICT(assessment_id,question) DO UPDATE SET answer=excluded.answer').bind(uid(),id,q,JSON.stringify(v))),db().prepare('UPDATE assessments SET classification=?,status=?,updated_at=? WHERE id=?').bind(classify(answers),'Assessment Completed',now(),id),event(id,'Assessment Completed')]);return json({id,classification:classify(answers)});}
 }
 if(path[0]==='auth'&&path[1]==='request'&&post){const data=z.object({email:z.string().trim().email().max(254),assessmentId:z.string().uuid().optional(),name:z.string().trim().min(1).max(100).optional(),country:z.string().length(2).optional()}).parse(b);const email=data.email.toLowerCase();await limit('email:'+await hash(email),4,900);await limit('request:'+await hash(ip),15,900);let a:any=null;if(data.assessmentId){a=await owned(req,data.assessmentId);if(a.user_id)fail('This assessment is already verified.',409);if(!a.classification)fail('Finish your assessment first.');if(!data.name)fail('Please enter your name.');const country=countries.find(c=>c.code===data.country);if(!country)fail('Select a country.');await db().batch([db().prepare('UPDATE assessments SET email=?,name=?,country_code=?,country_name=?,status=?,updated_at=? WHERE id=?').bind(email,data.name,country.code,country.name,'Email Submitted',now(),a.id),event(a.id,'Email Submitted')]);}
 const existing=await first('SELECT id FROM users WHERE email=?',email);const id=uid();if(!a&&!existing)return json({challenge:id,status:'requested',message:'If an account exists, a verification email will arrive shortly.'});
 const bytes=crypto.getRandomValues(new Uint32Array(1));const code=String(bytes[0]%1000000).padStart(6,'0');await db().batch([db().prepare('UPDATE email_verification SET consumed_at=? WHERE email=? AND consumed_at IS NULL').bind(now(),email),db().prepare('INSERT INTO email_verification (id,assessment_id,email,code_hash,attempts,expires_at,created_at) VALUES (?,?,?,?,0,?,?)').bind(id,a?.id||null,email,await hash(id+':'+code),Date.now()+600000,now())]);const mail=await sendMail(a?.id||null,email,'verification','Verify your AI//CONFIG email',emailFrame('One code. Your configuration.',`<p>Your verification code is:</p><p style="font:32px monospace;letter-spacing:8px">${code}</p><p>Expires in 10 minutes. Do not share this code. If you did not request it, ignore this email.</p>`));return json({challenge:id,status:mail.status,message:mail.status==='sent'?'Check your inbox for your six-digit code.':mail.status==='preview'?'Email delivery is not configured. A secure preview is available to your administrator; no email has been sent.':'Email delivery failed. Please request another code shortly.'});}
 if(path[0]==='auth'&&path[1]==='verify'&&post){const data=z.object({challenge:z.string().uuid(),code:z.string().regex(/^\d{6}$/)}).parse(b);await limit('verify:'+await hash(ip),30,900);const v=await first('UPDATE email_verification SET attempts=attempts+1 WHERE id=? AND consumed_at IS NULL AND expires_at>? AND attempts<5 RETURNING *',data.challenge,Date.now());if(!v||v.code_hash!==await hash(data.challenge+':'+data.code))fail('Invalid or expired code. Request a new code after five attempts.');const consumed=await first('UPDATE email_verification SET consumed_at=? WHERE id=? AND consumed_at IS NULL RETURNING id',now(),v.id);if(!consumed)fail('This code has already been used.',409);let u=await first('SELECT * FROM users WHERE email=?',v.email);if(v.assessment_id){const a=await first('SELECT * FROM assessments WHERE id=?',v.assessment_id);if(a.user_id)fail('Assessment is already attached to an account.',409);if(a.email!==v.email)fail('The assessment email changed. Request a new code.',409);const newUser=!u;const userId=u?.id||uid();const ops=[];if(newUser)ops.push(db().prepare('INSERT INTO users (id,email,name,country_code,country_name,role,created_at) VALUES (?,?,?,?,?,?,?)').bind(userId,v.email,a.name,a.country_code,a.country_name,'user',now()));ops.push(db().prepare('UPDATE assessments SET user_id=?,status=?,updated_at=? WHERE id=?').bind(userId,'Email Verified',now(),a.id),event(a.id,'Email Verified'));if(newUser)ops.push(event(a.id,'Account Created'));await db().batch(ops);u=await first('SELECT * FROM users WHERE id=?',userId);}
 if(!u)fail('No account found. Complete an assessment first.',404);const session=token();await db().prepare('INSERT INTO sessions (token_hash,user_id,expires_at) VALUES (?,?,?)').bind(await hash(session),u.id,Date.now()+7*86400000).run();let generated=true;if(v.assessment_id){try{await attachRecommendation(v.assessment_id);}catch{generated=false;}}return json({ok:true,assessmentId:v.assessment_id,generated},200,[cookieHeader(req,'aic_session',session,7*86400)]);}
 if(path[0]==='dashboard'){const u=await user(req);if(!u)fail('Sign in to view your configurations.',401);if(!path[1]){const r=await query('SELECT id,status,classification,created_at FROM assessments WHERE user_id=? ORDER BY created_at DESC',u.id);return json({user:u,assessments:r.results});}const a=await owned(req,path[1],true);const answers=await readAnswers(a.id);const rec=await first('SELECT approved FROM recommendations WHERE assessment_id=?',a.id);const products=rec?.approved?(await query('SELECT p.*,pr.reason FROM products p JOIN product_recommendations pr ON pr.product_id=p.product_id WHERE pr.assessment_id=? AND p.country=? AND p.inventory_status=?',a.id,a.country_code,'In stock')).results:[];return json({assessment:a,answers,recommendation:rec?.approved?JSON.parse(rec.approved):null,products,timeline:(await query("SELECT event,created_at FROM funnel_events WHERE assessment_id=? AND event NOT IN ('Product Click','Purchase') ORDER BY created_at",a.id)).results});}
 if(path[0]==='product-click'&&post){const a=await owned(req,z.string().uuid().parse(b.assessmentId),true);const p=await first('SELECT p.* FROM products p JOIN product_recommendations pr ON p.product_id=pr.product_id JOIN recommendations r ON r.assessment_id=pr.assessment_id WHERE pr.assessment_id=? AND p.product_id=? AND r.approved IS NOT NULL AND p.country=? AND p.inventory_status=?',a.id,z.string().uuid().parse(b.productId),a.country_code,'In stock');if(!p)fail('Product not available.',404);await event(a.id,'Product Click',p.product_id).run();return json({url:p.purchase_url});}
 if(path[0]==='admin'){
 const actor=await admin(req);if(path[1]==='overview'){const metrics=await first("SELECT COUNT(*) AS total,SUM(status='Pending Human Review') AS pending,SUM(status IN ('Approved','Email Sent','Report Preview Ready')) AS approved,SUM(email IS NOT NULL AND user_id IS NULL) AS unverified,SUM(status='Email Sent') AS sent FROM assessments");return json({metrics,services:{ai:!!config().OPENAI_API_KEY,email:!!config().RESEND_API_KEY&&!!config().EMAIL_FROM},funnel:(await query('SELECT event,COUNT(*) AS count FROM funnel_events GROUP BY event')).results});}
 if(path[1]==='assessments'&&!path[2]){const rows=(await query("SELECT a.*, (SELECT answer FROM assessment_answers x WHERE x.assessment_id=a.id AND x.question='workloads') AS workloads, (SELECT answer FROM assessment_answers x WHERE x.assessment_id=a.id AND x.question='budget') AS budget FROM assessments a ORDER BY created_at DESC LIMIT 500")).results;return json({assessments:rows});}
 if(path[1]==='assessments'&&path[2]){const id=path[2],a=await first('SELECT * FROM assessments WHERE id=?',id);if(!a)fail('Assessment not found.',404);const answers=await readAnswers(id);const r=await first('SELECT * FROM recommendations WHERE assessment_id=?',id);
 if(!post)return json({assessment:a,answers,recommendation:r?JSON.parse(r.draft):null,baseline:r?JSON.parse(r.baseline):null,revision:r?.revision||0,reviews:(await query('SELECT * FROM admin_reviews WHERE assessment_id=? ORDER BY created_at DESC',id)).results,revisions:(await query('SELECT id,author,created_at FROM recommendation_revisions WHERE assessment_id=? ORDER BY created_at DESC',id)).results,emails:(await query('SELECT * FROM email_events WHERE assessment_id=? ORDER BY created_at DESC LIMIT 15',id)).results,timeline:(await query('SELECT event,created_at FROM funnel_events WHERE assessment_id=? ORDER BY created_at',id)).results,products:(await query('SELECT * FROM products WHERE country=? AND inventory_status=?',a.country_code||'','In stock')).results,matches:(await query('SELECT * FROM product_recommendations WHERE assessment_id=?',id)).results});
 if(!a.user_id)fail('Verify the customer email before generating or approving a report.',409);const action=z.enum(['regenerate','save','approve','send','reject','match','unmatch']).parse(b.action);if(action==='regenerate'){const generated=await generate(answers);const baseline=recommend(answers);await db().batch([db().prepare('INSERT INTO recommendations (assessment_id,baseline,draft,revision,created_at,updated_at) VALUES (?,?,?,1,?,?) ON CONFLICT(assessment_id) DO UPDATE SET baseline=excluded.baseline,draft=excluded.draft,approved=NULL,revision=recommendations.revision+1,updated_at=excluded.updated_at').bind(id,JSON.stringify(baseline),JSON.stringify(generated),now(),now()),db().prepare('UPDATE assessments SET status=?,updated_at=? WHERE id=?').bind('Pending Human Review',now(),id),db().prepare('INSERT INTO recommendation_revisions (id,assessment_id,content,author,created_at) VALUES (?,?,?,?,?)').bind(uid(),id,JSON.stringify(generated),actor,now()),event(id,'AI Recommendation Generated'),event(id,'Pending Human Review')]);return json({ok:true});}
 if(!r)fail('Generate the recommendation first.',409);
 if(action==='match'||action==='unmatch'){const p=await first('SELECT * FROM products WHERE product_id=?',z.string().uuid().parse(b.productId));if(!p)fail('Product not found.',404);if(action==='unmatch'){await db().prepare('DELETE FROM product_recommendations WHERE assessment_id=? AND product_id=?').bind(id,p.product_id).run();return json({ok:true});}const rec=JSON.parse(r.draft);if(rec.architecture==='Cloud')fail('Cloud-only plans do not need hardware products.');if(p.country!==a.country_code||p.inventory_status!=='In stock')fail('Product must be available in the customer’s country.');if(p.category==='GPU'&&p.capacity<rec.minVram)fail('GPU memory is below the baseline.');if(p.category==='RAM'&&p.capacity<rec.minRam)fail('Memory kit is below the baseline.');const reason=z.string().trim().min(12).max(1000).parse(b.reason);await db().prepare('INSERT INTO product_recommendations (id,assessment_id,product_id,reason,created_at) VALUES (?,?,?,?,?) ON CONFLICT(assessment_id,product_id) DO UPDATE SET reason=excluded.reason').bind(uid(),id,p.product_id,reason,now()).run();return json({ok:true});}
 const notes=z.string().max(5000).parse(b.notes||'');const revision=z.number().int().parse(b.revision);if(revision!==r.revision)fail('Another review changed this report. Reload before saving.',409);const draft=action==='reject'?JSON.parse(r.draft):validated(()=>validateRevision(b.recommendation,JSON.parse(r.baseline),answers));draft.aiStatus=JSON.parse(r.draft).aiStatus;const approved=action==='approve'||action==='send';const status=action==='reject'?'Rejected':approved?'Approved':'Pending Human Review';const serialized=JSON.stringify(draft);
 const updated=await first('UPDATE recommendations SET draft=?,approved=?,revision=revision+1,updated_at=? WHERE assessment_id=? AND revision=? RETURNING revision',serialized,approved?serialized:null,now(),id,revision);if(!updated)fail('Another reviewer saved first. Reload this page.',409);await db().batch([db().prepare('UPDATE assessments SET status=?,updated_at=? WHERE id=?').bind(status,now(),id),db().prepare('INSERT INTO recommendation_revisions (id,assessment_id,content,author,created_at) VALUES (?,?,?,?,?)').bind(uid(),id,serialized,actor,now()),db().prepare('INSERT INTO admin_reviews (id,assessment_id,admin,action,notes,created_at) VALUES (?,?,?,?,?,?)').bind(uid(),id,actor,action,notes,now()),event(id,approved?'Recommendation Approved':status)]);let delivery=null;if(action==='send'){delivery=await reportMail(a,draft,url.origin);if(delivery.status==='sent'){await db().batch([db().prepare('UPDATE assessments SET status=?,updated_at=? WHERE id=?').bind('Email Sent',now(),id),event(id,'Report Sent')]);}else if(delivery.status==='preview'){await db().prepare('UPDATE assessments SET status=?,updated_at=? WHERE id=?').bind('Report Preview Ready',now(),id).run();}}
 return json({ok:true,delivery});}
 if(path[1]==='products'){if(!post)return json({products:(await query('SELECT * FROM products ORDER BY updated_at DESC')).results});const p=z.object({product_id:z.string().uuid().optional(),brand:z.string().min(1).max(100),product_name:z.string().min(1).max(160),category:z.enum(['RAM','NVMe SSD','SATA SSD','NAS storage','GPU','Mini PC','Workstation','Networking']),capacity:z.number().min(0).max(100000),interface:z.string().min(1).max(100),specifications:z.string().min(1).max(3000),compatibility:z.string().min(1).max(2000),country:z.string().length(2),price:z.number().min(0).max(10000000),currency:z.string().regex(/^[A-Z]{3}$/),inventory_status:z.enum(['In stock','Out of stock','Unverified']),purchase_url:z.string().url().max(2000)}).parse(b);if(!countries.some(c=>c.code===p.country))fail('Invalid country.');if(!p.purchase_url.startsWith('https://'))fail('Use a secure HTTPS purchase link.');try{new Intl.NumberFormat('en',{style:'currency',currency:p.currency});}catch{fail('Invalid currency.');}const id=p.product_id||uid();await db().prepare('INSERT INTO products (product_id,brand,product_name,category,capacity,interface,specifications,compatibility,country,price,currency,inventory_status,purchase_url,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(product_id) DO UPDATE SET brand=excluded.brand,product_name=excluded.product_name,category=excluded.category,capacity=excluded.capacity,interface=excluded.interface,specifications=excluded.specifications,compatibility=excluded.compatibility,country=excluded.country,price=excluded.price,currency=excluded.currency,inventory_status=excluded.inventory_status,purchase_url=excluded.purchase_url,updated_at=excluded.updated_at').bind(id,p.brand,p.product_name,p.category,p.capacity,p.interface,p.specifications,p.compatibility,p.country,Math.round(p.price*100),p.currency,p.inventory_status,p.purchase_url,now()).run();return json({id});}
 }
 return json({error:'Not found.'},404);
 }catch(e:any){if(e instanceof z.ZodError)return json({error:e.issues.map(i=>i.path.join('.')+': '+i.message).join('; ')},400);if(e.status)return json({error:e.message},e.status);console.error('AI_CONFIG_REQUEST_FAILED',e?.message);return json({error:'We couldn’t complete that request. Your input is preserved. Please try again.'},500);}}
export const GET=handle;export const POST=handle;
