import assert from 'node:assert/strict';
const origin='http://localhost:5173';
function client(){let cookies={};return {async call(path,body,expected=200){const r=await fetch(origin+path,{method:body===undefined?'GET':'POST',headers:{Origin:origin,'Content-Type':'application/json',Cookie:Object.entries(cookies).map(([k,v])=>`${k}=${v}`).join('; ')},body:body===undefined?undefined:JSON.stringify(body),redirect:'manual'});for(const c of r.headers.getSetCookie()){const [k,v]=c.split(';')[0].split('=');cookies[k]=v;}const text=await r.text();let j;try{j=JSON.parse(text);}catch{j={raw:text.slice(0,300)};}assert.equal(r.status,expected,`${path}: ${JSON.stringify(j)}`);return j;}};}
const visitor=client(),admin=client(),stranger=client();
await admin.call('/signin-with-chatgpt?return_to=/admin',undefined,302);
assert.equal((await admin.call('/api/me')).admin,true,'local admin sign-in');
await stranger.call('/api/admin/overview',undefined,403);
await stranger.call('/api/dashboard',undefined,401);
const answers={persona:'Developer',workloads:['Coding Assistant','Company Knowledge AI / RAG','AI Agents and automation'],users:'2–5',privacy:'Some of it',data:'1–5TB',automation:'Yes, regularly',hardware:['Mac'],device:'Test Mac, 64GB',budget:'$2,000–5,000',technical:'Developer / AI engineer'};
const {id}=await visitor.call('/api/assessments',{},201);
await stranger.call('/api/assessment/'+id,undefined,401);
await visitor.call('/api/assessment/'+id+'/complete',{answers:{...answers,users:'invalid'}},400);
const complete=await visitor.call('/api/assessment/'+id+'/complete',{answers});assert.equal(complete.classification,'Hybrid');
const preliminary=await visitor.call('/api/assessment/'+id);assert.ok(!preliminary.recommendation);
const auth=await visitor.call('/api/auth/request',{assessmentId:id,name:'Test Developer',email:`qa-${Date.now()}@example.com`,country:'US'});assert.equal(auth.status,'preview');assert.ok(!auth.code);
await visitor.call('/api/auth/verify',{challenge:auth.challenge,code:'xxxxxx'},400);
const review=await admin.call('/api/admin/assessments/'+id);const code=review.emails.find(e=>e.kind==='verification').html.match(/letter-spacing:8px">(\d{6})/)[1];
await visitor.call('/api/auth/verify',{challenge:auth.challenge,code});
await visitor.call('/api/auth/verify',{challenge:auth.challenge,code},400);
const pending=await visitor.call('/api/dashboard/'+id);assert.equal(pending.assessment.status,'Pending Human Review');assert.equal(pending.recommendation,null);
const generated=await admin.call('/api/admin/assessments/'+id);assert.equal(generated.recommendation.architecture,'Hybrid');assert.ok(generated.recommendation.minVram>=24);
const bad={...generated.recommendation,minVram:1};await admin.call('/api/admin/assessments/'+id,{action:'approve',revision:generated.revision,recommendation:bad},400);
const edited={...generated.recommendation,explanation:generated.recommendation.explanation+'\nReviewed: benchmark existing Mac before any purchase.'};
await admin.call('/api/admin/assessments/'+id,{action:'save',revision:generated.revision,recommendation:edited,notes:'Test review: existing hardware first.'});
await admin.call('/api/admin/assessments/'+id,{action:'approve',revision:generated.revision,recommendation:edited},409);
const saved=await admin.call('/api/admin/assessments/'+id);assert.equal(saved.recommendation.explanation,edited.explanation);
const approval=await admin.call('/api/admin/assessments/'+id,{action:'send',revision:saved.revision,recommendation:saved.recommendation,notes:'Approved for preview-mode workflow testing.'});assert.equal(approval.delivery.status,'preview');
const final=await visitor.call('/api/dashboard/'+id);assert.equal(final.assessment.status,'Report Preview Ready');assert.equal(final.recommendation.explanation,edited.explanation);assert.equal(final.products.length,0);
await stranger.call('/api/dashboard/'+id,undefined,401);await visitor.call('/api/admin/assessments/'+id,undefined,403);
const finalReview=await admin.call('/api/admin/assessments/'+id);assert.ok(finalReview.emails.some(e=>e.kind==='report'&&e.html.includes('Reviewed: benchmark existing Mac')&&e.status==='preview'));assert.ok(finalReview.reviews.length>=2);
const product={brand:'QA Brand',product_name:'Test 64GB kit',category:'RAM',capacity:64,interface:'DDR5 DIMM',specifications:'Synthetic fixture, not a real commercial recommendation.',compatibility:'Requires compatible DDR5 desktop platform; reviewer confirms fit.',country:'US',price:200,currency:'USD',inventory_status:'In stock',purchase_url:'https://example.com/test-product'};
const prod=await admin.call('/api/admin/products',product);await visitor.call('/api/admin/products',product,403);
await admin.call('/api/admin/assessments/'+id,{action:'match',productId:prod.id,reason:'Test match: 64 GB meets baseline; interface reviewed for a planned desktop.'});
assert.equal((await visitor.call('/api/dashboard/'+id)).products.length,1);
assert.equal((await visitor.call('/api/product-click',{assessmentId:id,productId:prod.id})).url,product.purchase_url);
await admin.call('/api/admin/products',{...product,product_id:prod.id,inventory_status:'Out of stock'});
assert.equal((await visitor.call('/api/dashboard/'+id)).products.length,0);
await visitor.call('/api/product-click',{assessmentId:id,productId:prod.id},404);
await admin.call('/api/admin/assessments/'+id,{action:'regenerate'});assert.equal((await visitor.call('/api/dashboard/'+id)).recommendation,null,'regeneration returns to review and hides the report');
console.log(JSON.stringify({passed:true,assessmentId:id,checks:['assessment validation','ownership isolation','email preview','OTP verification and replay rejection','account creation','deterministic sizing','admin authorization','draft revision conflict','approval and email preview','dashboard release','regeneration revokes approval']}));
