export const questions = [
 {id:'persona',title:'Who are you building AI for?',help:'Let’s start with you. We’ll adapt the next questions to your setup.',options:['Just me','My family','Creator','Developer','My team / company','I’m building AI products']},
 {id:'workloads',title:'What would you like AI to do?',help:'Choose everything that matters. Knowledge AI / RAG means finding answers in your own documents.',multi:true,options:['Private ChatGPT','Coding Assistant','Company Knowledge AI / RAG','AI Agents and automation','Image Generation','Video Generation','Voice / Transcription','Home AI / Home Assistant / NAS','AI Development','Fine-tuning / Training','I’m not sure yet']},
 {id:'users',title:'How many people will use it?',help:'Total users aren’t the same as simultaneous requests. We’ll make a conservative assumption and flag it for review.',options:['1','2–5','6–10','11–30','30+']},
 {id:'privacy',title:'How private does your data need to be?',help:'This is about the data AI works with — documents, code, recordings, and conversations.',options:['Not really','Some of it','Absolutely'],details:['I’m comfortable using cloud AI.','Sensitive data should stay local.','My data cannot leave my device or company.']},
 {id:'data',title:'How much private data will AI work with?',help:'An estimate is fine. Think documents, photos, recordings, and shared files.',options:['Less than 100GB','100GB–1TB','1–5TB','5–20TB','20TB+','I don’t know']},
 {id:'automation',title:'Should AI work in the background?',help:'For example: email automation, file processing, company workflows, monitoring, home automation, or scheduled AI agents.',options:['No','Occasionally','Yes, regularly','Yes, 24/7']},
 {id:'hardware',title:'What hardware do you already own?',help:'The best upgrade might be using what you have. Select all that apply.',multi:true,options:['Mac','Windows PC','Gaming PC','NAS','Mini PC','Server','Nothing yet']},
 {id:'budget',title:'What’s your approximate hardware budget?',help:'In USD, before tax, shipping, electricity, and subscriptions. We won’t stretch a budget just to recommend a machine.',options:['Under $500','$500–1,000','$1,000–2,000','$2,000–5,000','$5,000–10,000','$10,000+','Not sure']},
 {id:'technical',title:'How hands-on would you like to be?',help:'A configuration should fit your comfort level as well as your workload.',options:['I just want it to work','Comfortable installing software','Comfortable upgrading hardware','Advanced / Homelab','Developer / AI engineer']}
];
export type Answers=Record<string,string|string[]>;
export function validateAnswers(a:any):Answers{if(!a||typeof a!=='object')throw new Error('Please complete the assessment.');const out:Answers={};for(const q of questions){const v=a[q.id];if(q.multi){if(!Array.isArray(v)||v.length<1||v.length>q.options.length||v.some(x=>!q.options.includes(x))||new Set(v).size!==v.length)throw new Error(`Please answer: ${q.title}`);if(v.length>1&&(v.includes('Nothing yet')||v.includes('I’m not sure yet')))throw new Error('Choose either “not sure / nothing yet” or specific options.');out[q.id]=v;}else{if(typeof v!=='string'||!q.options.includes(v))throw new Error(`Please answer: ${q.title}`);out[q.id]=v;}}out.device=typeof a.device==='string'?a.device.slice(0,500):'';return out;}
export function classify(a:Answers){const w=a.workloads as string[]||[];if(a.privacy==='Absolutely')return 'Local';if(a.privacy==='Some of it'||a.automation==='Yes, 24/7'||w.includes('Home AI / Home Assistant / NAS'))return 'Hybrid';return 'Cloud';}
const codes='AF AL DZ AS AD AO AI AQ AG AR AM AW AU AT AZ BS BH BD BB BY BE BZ BJ BM BT BO BQ BA BW BV BR IO BN BG BF BI CV KH CM CA KY CF TD CL CN CX CC CO KM CG CD CK CR CI HR CU CW CY CZ DK DJ DM DO EC EG SV GQ ER EE SZ ET FK FO FJ FI FR GF PF TF GA GM GE DE GH GI GR GL GD GP GU GT GG GN GW GY HT HM VA HN HK HU IS IN ID IR IQ IE IM IL IT JM JP JE JO KZ KE KI KP KR KW KG LA LV LB LS LR LY LI LT LU MO MG MW MY MV ML MT MH MQ MR MU YT MX FM MD MC MN ME MS MA MZ MM NA NR NP NL NC NZ NI NE NG NU NF MK MP NO OM PK PW PS PA PG PY PE PH PN PL PT PR QA RE RO RU RW BL SH KN LC MF PM VC WS SM ST SA SN RS SC SL SG SX SK SI SB SO ZA GS SS ES LK SD SR SJ SE CH SY TW TJ TZ TH TL TG TK TO TT TN TR TM TC TV UG UA AE GB US UM UY UZ VU VE VN VG VI WF EH YE ZM ZW'.split(' ');
const dn=new Intl.DisplayNames(['en'],{type:'region'});
export const countries=codes.map(code=>({code,name:dn.of(code)||code})).sort((a,b)=>a.name.localeCompare(b.name));
